Task 1

In [4]:
import numpy as np

arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Task 2

In [5]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task 3

In [9]:
a = np.flip(arr)
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Task 4

In [10]:
mat = np.arange(9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Task 5

In [15]:
arr = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(arr)[0])

[0 1 4]


Task 6

In [16]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task 7

In [57]:
mat = np.random.random((3, 3))
print(mat.min())
print(mat.max())

0.08465556579471367
0.8945547607941917


Task 8

In [65]:
arr = np.random.random((5, 5))
scaled_arr = np.floor(arr * (10 - 1) + 1)
print(scaled_arr)

min_val = scaled_arr.min()
max_val = scaled_arr.max()
normalized_matrix = (scaled_arr - min_val) / (max_val - min_val)

print(normalized_matrix)

[[8. 5. 3. 5. 5.]
 [8. 9. 1. 3. 5.]
 [5. 1. 8. 4. 4.]
 [5. 2. 8. 7. 7.]
 [3. 2. 8. 2. 7.]]
[[0.875 0.5   0.25  0.5   0.5  ]
 [0.875 1.    0.    0.25  0.5  ]
 [0.5   0.    0.875 0.375 0.375]
 [0.5   0.125 0.875 0.75  0.75 ]
 [0.25  0.125 0.875 0.125 0.75 ]]


Task 9

In [ ]:
array = np.array([1, 3, 5, 11, 15, 20, 25])
target = 14

# Find the index of the closest value
closest_index = np.abs(array - target).argmin()

# Get the closest value
closest_value = array[closest_index]

print(closest_value)


Closest value to 14 is 15


Task 10

In [74]:
array = np.array([[5, 9, 3], [10, 2, 15], [6, 7, 8]])

array[np.arange(array.shape[0]), array.argmax(axis=1)] = 0

print(array)


[[ 5  0  3]
 [10  2  0]
 [ 6  7  0]]


Task 11

In [77]:
array = np.array([2, 3, 2, 5, 8, 3, 3, 7, 2, 3, 5, 5, 5, 5])

el = np.bincount(array).argmax()
print(el)

5


Task 12

In [78]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix_product = np.dot(array, array.T)

print(matrix_product)


[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


Task 13

In [79]:
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])

new = np.linalg.det(matrix)

print(new)

-306.0


Task 14

In [80]:
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])

det = np.linalg.det(matrix)

if det != 0:
    invers = np.linalg.inv(matrix)
    print(invers)
else:
    print("not exist")


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
